### ISSUE TITLE
Command names are bad

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-morph-all-players#2]
The commands should be added to the original .morph command imo

```
.morph all 999
.demorph all
```

Or even better
```
.morph reset all
```

but that also means that we should revamp the .morph command and remove the .demorph command, see https://github.com/azerothcore/azerothcore-wotlk/issues/2629

**Comment by pangolp** [comment]
In an attempt to keep that repository up to date, I'm going to close this topic. But if I'm wrong, feel free to reopen it.
